[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/for-schools"
  to = "/for-schools.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
